config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # email_check_env
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # check_sidekiq
  require "sidekiq/web"
  require "sidekiq-scheduler/web"
  mount Sidekiq::Web => "/sidekiq"

  # for_my_app_route
  root "static_page#top"
  resource :description, only: %i[show]

  resource :setting, only: %i[show]
  get "agreement", to: "settings#agreement", as: "agreement"
  get "plivacy_policy", to: "settings#privacy_policy", as: "plivacy_policy"
  resource :contact, only: %i[show new create]

  resource :profile, only: %i[new create edit update]
  get "profile/:id", to: "profiles#show", as: "user_profile"

  resources :notifications, only: %i[index]

  get "friends/:id", to: "friends#chat_board", as: "friend_chat"
  post "friends/:user_id", to: "friends#create", as: "new_friend"
  put "friends/:id", to: "friends#approve", as: "approve_friend"
  delete "friends/:id", to: "friends#refuse", as: "refuse_friend"
  patch "friend/:user_id", to: "friends#blocked", as: "block_friend"


  resources :rooms, only: %i[new index show create edit update destroy] do
    collection do
      get :search
    end
    member do
      get :chat_board
      delete :leave
      patch "kick/:user_id", to: "rooms#kick", as: :kick_user
    end
    resources :permits, only: %i[create destroy] do
      member do
        post :approve
        delete :refuse
      end
    end
  end

  resources :boards, only: %i[new index show create destroy] do
    collection do
      get :search
    end
    resources :comments, only: %i[create] do
      get "media_show/:id", to: "comments#media_show", as: "media"
    end
  end

  # for_admin_route
  namespace :admin do
    root "dashboards#index"
    resource :dashboard, only: %i[index]
    devise_scope :user do
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      delete "logout", to: "sessions#destroy"
      get "user_edit/:id", to: "registrations#edit", as: "user_edit"
      put "user_update/:id", to: "registrations#update", as: "user_update"
      delete "user_destroy/:id", to: "registrations#destroy", as: "user_destroy"
    end
    resources :users, only: %i[index show] do
      collection do
        get :search
      end
    end
    resources :profiles, only: %i[show edit update]
    resources :rooms, only: %i[index show destroy] do
      collection do
        get :search
      end
    end
    resources :messages, only: %i[destroy]
    resources :games, only: %i[index create destroy]
    resources :tags, only: %i[index create destroy]
    resources :contacts, only: %i[index show destroy] do
      collection do
        get :search
      end
    end
    resources :boards, only: %i[index show destroy] do
      collection do
        get :search
      end
      resources :comments, only: %i[destroy]
    end
  end
end

app/views/shared/_before_login_header.html.erb
<nav class="navbar navbar-expand-lg" id="header-nav">
  <div class="container-fluid">
    <a href="/" class="ms-3"><%= image_tag '1.png', size:"230x90" %></a>
    <div class="navbar-nav mt-3 me-5">
      <p><%= link_to new_user_session_path do %>
        <i class="bi bi-box-arrow-in-right me-1"></i><%= t('header.login') %>
      <% end %></p>
      <%= link_to setting_path do %><i class="bi bi-gear ms-3"></i><% end %>
    </div>
  </div>
</nav>

app/views/shared/_before_login_sidebar.html.erb
<div class="d-flex flex-column position-relative" id="sidebar-nav">
  <div class="ms-3 mt-4">
    <div class="navbar-item">
      <p><%= link_to rooms_path do %><i class="bi bi-controller me-1"></i><%= t('sidebar.invite') %><% end %></p>
    </div>
    <div class="navbar-item">
      <p><%= link_to boards_path do %><i class="bi bi-chat-right-text me-1"></i><%= t("sidebar.board") %><% end %></p>
    </div>
    <div class="navbar-item">
      <p><%= link_to description_path do %><i class="bi bi-question-circle me-1"></i><%= t("sidebar.description") %><% end %></p>
    </div>
  </div>
</div>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false" class="alert alert-danger">
    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>    

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg" id="header-nav">
  <div class="container-fluid">
    <a href="/" class="ms-3"><%= image_tag '1.png', size:"230x90" %></a>
    <div class="navbar-nav mt-3 me-5">
      <div class="me-3" id="notification_user" data-id="<%= current_user.id %>">
        <div id="notification_field">
          <%= link_to notifications_path do %>
            <i class="bi bi-bell position-relative"></i>
            <div class="position-absolute top-25 start-75 translate-middle badge rounded-pill text-bg-secondary"><%= "#{@notifications_count}" %></div>
          <% end %>
        </div>  
      </div>  
      <% if current_user.profile.present? %>
        <%= link_to user_profile_path(current_user), class: "mx-4 mb-2" do %>
          <%= image_tag current_user.profile.decorate.avatar_image(40, 40), class: "rounded-circle", id: "header-avatar" %>
        <% end %>
      <% end %>  
      <%= link_to setting_path do %><i class="bi bi-gear"></i><% end %>
    </div>
  </div>
</nav>

app/views/shared/_notification.html.erb
<div id="notification_field">
  <%= link_to notifications_path do %>
    <i class="bi bi-bell position-relative"></i>
      <div class="position-absolute top-25 start-75 translate-middle badge rounded-pill text-bg-secondary"><%= "#{notifications_count}" %></div>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<div class="d-flex flex-column position-relative" id="sidebar-nav">
  <div class="navbar-items ms-4 mt-4">
    <div class="navbar-item">
      <p><%= link_to user_profile_path(current_user) do %><i class="bi bi-person-circle me-1"></i><%= t('sidebar.profile') %><% end %></p>
    </div>
    <div class="navbar-item">
      <p><%= link_to rooms_path do %><i class="bi bi-controller me-1"></i><%= t('sidebar.invite') %><% end %></p>
    </div>
    <div class="navbar-item">
      <p><%= link_to boards_path do %><i class="bi bi-chat-right-text me-1"></i><%= t("sidebar.board") %><% end %></p>
    </div>
    <div class="navbar-item">
      <p><%= link_to description_path do %><i class="bi bi-question-circle me-1"></i><%= t("sidebar.description") %><% end %></p>
    </div>
    <div class="navbar-item ms-1 mt-5 pe-4">
      <div class="overflow-auto p-2" id="friend-index">
        <p class="ps-2"><i class="bi bi-person-heart me-1"></i><%= t('sidebar.friend') %></p>
        <% Friend.find_friends_user(current_user).each do |user| %>
          <div class="d-flex dropdown-toggle mt-1" data-bs-toggle="dropdown" role="button" aria-expanded="false">
            <%= image_tag user.profile.decorate.avatar_image(30, 30), class: "rounded-circle", id: "friend-avatar" %>
            <span class="align-self-center ms-1 <%= 'active' if current_page?(friend_chat_path(Room.find_friend_chat(user, current_user))) %>" id="nickname"><%= user.profile.nickname %></span>
          </div>
          <ul class="dropdown-menu" id="drop_down">
            <li><%= link_to user_profile_path(user), class: "dropdown-item" do %><i class="bi bi-person-circle me-1"></i><%= t("sidebar.profile") %><% end %></li>
            <li><%= link_to friend_chat_path(Room.find_friend_chat(user, current_user)), class: "dropdown-item" do %><i class="bi bi-chat-dots me-1"></i><%= t("sidebar.friend_chat") %><% end %></li>
            <li><%= link_to block_friend_path(user), class: "dropdown-item link-danger", data: { turbo_method: :patch , turbo_confirm: t("sidebar.confirm_block") } do %><i class="bi bi-ban me-1"></i><%= t("sidebar.block_friend") %><% end %></li>
          </ul>  
        <% end %>
      </div>
    </div>
  </div>
  <div class="position-absolute bottom-0" style="width: 100%">
    <p class="ms-4">© 2025 zawawa03</p>
    <% if user_signed_in? %>
      <hr>
      <div class="d-flex justify-content-center mb-3">
        <%= link_to t('sidebar.logout'), destroy_user_session_path, id: "logout-link", data: { turbo_method: :delete } %>
      </div>
    <% end %>  
  </div>
</div>