config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # email_check_env
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # check_sidekiq
  require "sidekiq/web"
  require "sidekiq-scheduler/web"
  mount Sidekiq::Web => "/sidekiq"

  # for_my_app_route
  root "static_page#top"
  resource :description, only: %i[show]

  resource :setting, only: %i[show]
  get "agreement", to: "settings#agreement", as: "agreement"
  get "plivacy_policy", to: "settings#privacy_policy", as: "plivacy_policy"
  resource :contact, only: %i[show new create]

  resource :profile, only: %i[new create edit update]
  get "profile/:id", to: "profiles#show", as: "user_profile"

  resources :notifications, only: %i[index]

  get "friends/:id", to: "friends#chat_board", as: "friend_chat"
  post "friends/:user_id", to: "friends#create", as: "new_friend"
  put "friends/:id", to: "friends#approve", as: "approve_friend"
  delete "friends/:id", to: "friends#refuse", as: "refuse_friend"
  patch "friend/:user_id", to: "friends#blocked", as: "block_friend"


  resources :rooms, only: %i[new index show create edit update destroy] do
    collection do
      get :search
    end
    member do
      get :chat_board
      delete :leave
      patch "kick/:user_id", to: "rooms#kick", as: :kick_user
    end
    resources :permits, only: %i[create destroy] do
      member do
        post :approve
        delete :refuse
      end
    end
  end

  resources :boards, only: %i[new index show create destroy] do
    collection do
      get :search
    end
    resources :comments, only: %i[create] do
      get "media_show/:id", to: "comments#media_show", as: "media"
    end
  end

  # for_admin_route
  namespace :admin do
    root "dashboards#index"
    resource :dashboard, only: %i[index]
    devise_scope :user do
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      delete "logout", to: "sessions#destroy"
      get "user_edit/:id", to: "registrations#edit", as: "user_edit"
      put "user_update/:id", to: "registrations#update", as: "user_update"
      delete "user_destroy/:id", to: "registrations#destroy", as: "user_destroy"
    end
    resources :users, only: %i[index show] do
      collection do
        get :search
      end
    end
    resources :profiles, only: %i[show edit update]
    resources :rooms, only: %i[index show destroy] do
      collection do
        get :search
      end
    end
    resources :messages, only: %i[destroy]
    resources :games, only: %i[index create destroy]
    resources :tags, only: %i[index create destroy]
    resources :contacts, only: %i[index show destroy] do
      collection do
        get :search
      end
    end
    resources :boards, only: %i[index show destroy] do
      collection do
        get :search
      end
      resources :comments, only: %i[destroy]
    end
  end
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :creator, class_name: "User"
  belongs_to :game
  has_many :board_tags, dependent: :destroy
  has_many :tags, through: :board_tags
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < Admin::BaseController
  def index
    @boards = Board.includes(:creator).order(created_at: :DESC)
  end

  def show
    @board = Board.find(params[:id])
    @comments = @board.comments
  end

  def destroy
    @board = Board.find(params[:id])
    if @board.destroy
      redirect_to admin_boards_path, success: t(".destroy")
    else
      flash.now[:danger] = t(".not_destroy")
      render :index, status: :unprocessable_entity
    end
  end

  def search
    @search_board = AdminBoardSearchForm.new(search_params)
    @boards = @search_board.result
  end

  private

  def search_params
    params.require(:q).permit(:title, :game, :sort)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_room_option, only: %i[index search new create]
  skip_before_action :authenticate_user!, only: %i[index show search]
  skip_before_action :profile_check, only: %i[index show search]

  def index
    @boards = Board.includes(:creator).order(created_at: :DESC).page(params[:page]).per(10)
  end

  def show
    @board = Board.find(params[:id])
    @comments = @board.comments.where(parent_id: nil).order(created_at: :ASC).page(params[:page]).per(20)
    @number = 0
    @comment = Comment.new
    set_meta_tags(
      title: @board.title,
      description: "掲示板をチェック！",
      og: {
        title: @board.title,
        description: "掲示板をチェック！",
        url: board_path(@board),
        image: url_for(@board.game.picture)
      },
      twitter: {
        title: @board.title,
        description: "掲示板をチェック！",
        url: board_path(@board),
        image: url_for(@board.game.picture)
      }
    )
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, success: t(".create")
    else
      flash.now[:danger] = t(".not_create")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @board = Board.find(params[:id])
    if @board.destroy
      redirect_to boards_path, success: t(".destroy")
    else
      redirect_to boards_path, danger: t(".not_destroy")
    end
  end

  def search
    @board_search = BoardSearchForm.new(search_params)
    @boards = @board_search.result.page(params[:page]).per(10)
  end

  private

  def board_params
    params.require(:board).permit(:title, :game_id, tag_ids: [])
  end

  def set_room_option
    @game_options = Game.game_option
    @board_tag_options = Tag.search(3)
  end

  def search_params
    params.require(:q).permit(:word, :tag_id)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/admin/boards/_board.html.erb
<tr>
  <td><%= board.id %></td>
  <td><%= board.title %></td>
  <td><%= board.creator.id %></td>
  <td><%= board.creator.decorate.fullname %></td>
  <td><%= board.game.name %></td>
  <td><%= l board.created_at, format: :time %></td>
  <td><%= link_to t("default.show"), admin_board_path(board), class: "btn btn-primary" %></td>
  <td><%= link_to t("default.delete"), admin_board_path(board), class: "btn btn-danger",data: {turbo_method: :delete, turbo_confirm: t(".confirm") } %></td>
</tr>

app/views/admin/boards/_comment.html.erb
<tr>
  <td><%= comment.id %></td>
  <td><%= comment.parent_id %></td>
  <td><%= comment.user_id %></td>
  <td style="width: 400px;"><%= simple_format(comment.body) %></td>
  <td>
    <% if comment.media.attached? %>
      <div class="d-flex flex-wrap" style="width: 200px;">
        <% comment.media.each do |media| %>
          <%= image_tag media.variant(resize_to_limit: [100, 100]).processed %>
        <% end %>
      </div>  
    <% else %>
      <p>no_media</p>
    <% end %>  
  </td>
  <td><%= l comment.created_at, format: :time %></td>
  <td><%= link_to t("default.delete"), admin_board_comment_path(comment.board, comment), class: "btn btn-danger",data: {turbo_method: :delete, turbo_confirm: t(".confirm") } %></td>
</tr>

app/views/admin/boards/_search_form.html.erb
<%= form_with url: search_admin_boards_path, scope: :q, method: :get, locals: true do |f| %>
  <%= f.text_field :title, placeholder: "タイトル",class: "form-control" %>
  <div class="d-flex mt-1">
    <%= f.select :game, Game.all.map { |game| [ game.name, game.id ]}, { include_blank: t("admin.helpers.game") }, class: "form-select" %>
    <%= f.select :sort, [["降順", 0], ["昇順", 1]], { include_blank: t("admin.helpers.sort") }, class: "form-select ms-1" %>
    <%= f.submit t('admin.helpers.search'), class: "btn btn-primary ms-1" %>
  </div>  
<% end %>

app/views/admin/boards/index.html.erb
<% set_meta_tags title: t(".title") %>
<div class='container'>
  <div class='row my-4'>
    <div class='col-md-4'>
      <h1><%= t(".title") %></h1>
    </div>   
  </div>
  <div class='row'>
    <div class='col-md-10'>
      <table class="table">
        <thead>
         <tr>
          <th scope="col"><%= Board.human_attribute_name(:id) %></th>
          <th scope="col"><%= Board.human_attribute_name(:title) %></th>
          <th scope="col">creator_id</th>
          <th scope="col"><%= Board.human_attribute_name(:creator) %></th>
          <th scope="col"><%= Board.human_attribute_name(:game) %></th>
          <th scope="col"><%= Board.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
         </tr>
        </thead>
        <tbody>
          <%= render partial: 'board', collection: @boards %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/boards/search.html.erb
<% set_meta_tags title: t(".title") %>
<div class='container'>
  <div class='row my-4'>
    <div class='col-md-4'>
      <h1><%= t(".title") %></h1>
    </div>
    <div class="col-md-3">
      <%= render "search_form" %>
    </div>  
  </div>
  <div class='row'>
    <div class='col-md-10'>
      <table class="table">
        <thead>
         <tr>
          <th scope="col"><%= Board.human_attribute_name(:id) %></th>
          <th scope="col"><%= Board.human_attribute_name(:title) %></th>
          <th scope="col">creator_id</th>
          <th scope="col"><%= Board.human_attribute_name(:creator) %></th>
          <th scope="col"><%= Board.human_attribute_name(:game) %></th>
          <th scope="col"><%= Board.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
         </tr>
        </thead>
        <tbody>
          <%= render partial: 'board', collection: @boards %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/boards/show.html.erb
<% set_meta_tags title: t(".title") %>
<div class="container" id="admin_board_show">
  <div class="row p-5">
    <div class="col-md-10 mt-3">
      <h2><%= t(".title") %></h2>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row"><%= Board.human_attribute_name(:id) %></th>
            <td><%= @board.id %></td>
          </tr>
          <tr>
            <th scope="row"><%= Board.human_attribute_name(:title) %></th>
            <td><%= @board.title %></td>
          </tr>
          <tr>
            <th scope="row"><%= Board.human_attribute_name(:creator_id) %></th>
            <td><%= @board.creator.id %></td>
          </tr>
          <tr>
            <th scope="row"><%= Board.human_attribute_name(:creator) %></th>
            <td><%= @board.creator.decorate.fullname %></td>
          </tr>
          <tr>
            <th scope="row"><%= Board.human_attribute_name(:game) %></th>
            <td><%= @board.game.name %></td>
          </tr>
          <tr>
            <th scope="row"><%= Board.human_attribute_name(:created_at) %></th>
            <td><%= l @board.created_at, format: :time %></td>
          </tr>
        </tbody>
      </table>
      <%= link_to t("default.delete"), admin_board_path(@board), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: t(".confirm") } %>
    </div>
  </div>
  <div class="row">  
    <div class="col-md-12">  
      <h4><%= t(".comment_index") %></h4>
      <table class="table">
        <thead>
        <tr>
          <th scope="col"><%= Comment.human_attribute_name(:id) %></th>
            <th scope="col"><%= Comment.human_attribute_name(:parent_id) %></th>
            <th scope="col"><%= Comment.human_attribute_name(:user_id) %></th>
            <th scope="col"><%= Comment.human_attribute_name(:body) %></th>
            <th scope="col"><%= Comment.human_attribute_name(:media) %></th>
            <th scope="col"><%= Comment.human_attribute_name(:created_at) %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: 'comment', collection: @comments %>
        </tbody>
      </table>  
    </div>
  </div>
</div>