config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # email_check_env
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # check_sidekiq
  require "sidekiq/web"
  require "sidekiq-scheduler/web"
  mount Sidekiq::Web => "/sidekiq"

  # for_my_app_route
  root "static_page#top"
  resource :description, only: %i[show]

  resource :setting, only: %i[show]
  get "agreement", to: "settings#agreement", as: "agreement"
  get "plivacy_policy", to: "settings#privacy_policy", as: "plivacy_policy"
  resource :contact, only: %i[show new create]

  resource :profile, only: %i[new create edit update]
  get "profile/:id", to: "profiles#show", as: "user_profile"

  resources :notifications, only: %i[index]

  get "friends/:id", to: "friends#chat_board", as: "friend_chat"
  post "friends/:user_id", to: "friends#create", as: "new_friend"
  put "friends/:id", to: "friends#approve", as: "approve_friend"
  delete "friends/:id", to: "friends#refuse", as: "refuse_friend"
  patch "friend/:user_id", to: "friends#blocked", as: "block_friend"


  resources :rooms, only: %i[new index show create edit update destroy] do
    collection do
      get :search
    end
    member do
      get :chat_board
      delete :leave
      patch "kick/:user_id", to: "rooms#kick", as: :kick_user
    end
    resources :permits, only: %i[create destroy] do
      member do
        post :approve
        delete :refuse
      end
    end
  end

  resources :boards, only: %i[new index show create destroy] do
    collection do
      get :search
    end
    resources :comments, only: %i[create] do
      get "media_show/:id", to: "comments#media_show", as: "media"
    end
  end

  # for_admin_route
  namespace :admin do
    root "dashboards#index"
    resource :dashboard, only: %i[index]
    devise_scope :user do
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      delete "logout", to: "sessions#destroy"
      get "user_edit/:id", to: "registrations#edit", as: "user_edit"
      put "user_update/:id", to: "registrations#update", as: "user_update"
      delete "user_destroy/:id", to: "registrations#destroy", as: "user_destroy"
    end
    resources :users, only: %i[index show] do
      collection do
        get :search
      end
    end
    resources :profiles, only: %i[show edit update]
    resources :rooms, only: %i[index show destroy] do
      collection do
        get :search
      end
    end
    resources :messages, only: %i[destroy]
    resources :games, only: %i[index create destroy]
    resources :tags, only: %i[index create destroy]
    resources :contacts, only: %i[index show destroy] do
      collection do
        get :search
      end
    end
    resources :boards, only: %i[index show destroy] do
      collection do
        get :search
      end
      resources :comments, only: %i[destroy]
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :creator, class_name: "User"
  belongs_to :game
  has_many :room_tags, dependent: :destroy
  has_many :tags, through: :room_tags
  has_many :permits, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms
  has_many :permit_users, through: :permits, source: :user
  has_many :messages, dependent: :destroy

  attr_accessor :mode_tag_id

  validates :title, presence: true, length: { maximum: 50 }
  validates :body, length: { maximum: 255 }
  validates :people, presence: true,
    numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 50
    }

  enum category: { game: 0, friend: 1 }

  def user_join_room(user)
    users << user unless self.users.include?(user)
  end

  def find_permit(user)
    permits.find_by(user: user)
  end

  def self.find_friend_chat(user, current_user)
    Room.joins(:user_rooms).where(user_rooms: { user_id: [ user.id, current_user.id ] }).group("rooms.id").having("COUNT(DISTINCT user_rooms.user_id) = 2").where(category: 1).first
  end

  def have_blocked_user?(current_user)
    blocked_users = []
    self.users.each do |user|
      if Friend.find_blocked_user(user, current_user).present?
        blocked_users << user
      end
    end
    blocked_users.present?
  end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::BaseController
  def index
    @rooms = Room.includes(:creator)
  end

  def show
    @room = Room.find(params[:id])
    @users = @room.users
    @messages = @room.messages
  end

  def destroy
    @room = Room.find(params[:id])
    if @room.destroy
      redirect_to admin_rooms_path, success: t(".destroy")
    else
      flash.now[:danger] = t(".not_destroy")
      render :index, status: :unprocrssable_entity
    end
  end

  def search
    @room_search = AdminRoomSearchForm.new(search_params)
    @rooms = @room_search.result
  end

  private

  def search_params
    params.require(:q).permit(:title, :category, :game, :sort)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  require "faraday"
  skip_before_action :authenticate_user!, only: %i[ index show search ]
  skip_before_action :profile_check, only: %i[ index show search ]
  before_action :set_options, only: %i[ new create edit update index search ]
  before_action :joined_room, only: %i[index search show]

  def index
    @rooms = Room.includes(:creator).where(category: 0).order(created_at: :DESC).page(params[:page]).per(16)
  end

  def show
    @room = Room.find(params[:id])
    set_meta_tags(
      title: @room.title,
      description: "#{@room.creator.profile.nickname}さんのパーティー募集",
      og: {
        title: @room.title,
        description: "#{@room.creator.profile.nickname}さんのパーティー募集",
        url: room_path(@room),
        image: url_for(@room.game.picture)
      },
      twitter: {
        image: url_for(@room.game.picture)
      }
    )
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      @room.room_tags.create(tag_id: @room.mode_tag_id) if @room.mode_tag_id.present?
      @room.user_join_room(current_user)
      send_message(@room)
      redirect_to chat_board_room_path(@room), success: t(".create")
    else
      flash.now[:danger] = t(".not_create")
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      begin
        ActiveRecord::Base.transaction do
          @room.room_tags.destroy_all
          @room.room_tags.create(tag_id: @room.mode_tag_id) if @room.mode_tag_id.present?
          if @room.tag_ids.present?
            @room.tag_ids.each do |tag|
              @room.room_tags.create(tag_id: tag)
            end
          end
        end
        rescue => e
          flash.now[:danger] = t(".not_edit")
          render :edit, status: :unprocessable_entity
      end

      redirect_to chat_board_room_path(@room), success: t(".did_edit")
    else
      flash.now[:danger] = t(".not_edit")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @room = Room.find(params[:id])
    if @room.destroy
      redirect_to rooms_path, success: t(".destroy")
    else
      falsh.now[:danger] = t(".not_destroy")
      redirect_to :back, damger: t(".not_destroy")
    end
  end

  def chat_board
    @room = Room.find(params[:id])
    @users = @room.users
    @permits = @room.permits
    @messages = @room.messages
    @room.user_join_room(current_user)
    set_meta_tags(
      title: @room.title,
      description: "#{@room.creator.profile.nickname}さんのパーティー募集",
      og: {
        title: @room.title,
        description: "#{@room.creator.profile.nickname}さんのパーティー募集",
        url: room_path(@room),
        image: url_for(@room.game.picture)
      },
      twitter: {
        title: @room.title,
        description: "#{@room.creator.profile.nickname}さんのパーティー募集",
        url: room_path(@room),
        image: url_for(@room.game.picture)
      }
    )
  end

  def leave
    @room = Room.find(params[:id])
    @user_room = UserRoom.find_by(user: current_user, room: @room)
    if @user_room&.destroy
      @room.users.reload
      @room.destroy if @room.users.count.zero?
      redirect_to rooms_path, success: t(".leave")
    else
      flash.now[:danger] = t(".not_leave")
      render :chat_board, status: :unprocessable_entity
    end
  end

  def search
    @result = RoomSearchForm.new(search_params)
    @rooms = @result.result.page(params[:page]).per(16)
  end

  def kick
    @room = Room.find(params[:id])
    @user = User.find(params[:user_id])
    @user_room = UserRoom.find_by(user: @user, room: @room)
    if @user_room&.destroy
      redirect_to chat_board_room_path(@room), success: t(".kick")
    else
      flash.now[:danger] = t(".not_kick")
      render :chat_board, status: :unprocessable_entity
    end
  end

  private

  def room_params
    params.require(:room).permit(:title, :body, :people, :game_id, :mode_tag_id, tag_ids: [])
  end

  def search_params
    params.require(:q).permit(:word, :mode_tag, :style_tag, :ability_tag)
  end

  def set_options
    @game_options = Game.game_option
    @mode_tag_options = Tag.search(0)
    @style_tag_options = Tag.search(1)
    @ability_tag_options = Tag.search(2)
  end

  def joined_room
    if user_signed_in?
      @joined_rooms = Room.includes(:creator).where(category: 0).joins(:user_rooms).where(user_rooms: { user_id: current_user.id }).order(created_at: :DESC)
    end
  end

  def send_message(room)
    connection = Faraday.new(
      url: "https://discord.com/api/webhooks/1438005650566283344/lD4s1qXvqArcpz11HQAuo8eAyE5Gxm2bxidvdV447DYZ5HRdRPqml6R0F_BiXfsfSG1i"
      ) do |f|
      f.request :json
      f.adapter Faraday.default_adapter
    end

    data = {
      embeds: [
        {
          type: "link",
          title: "【#{room.game.name}】",
          thumbnail: { url: url_for(room.game.picture) },
          description: "#{room.title}",
          footer: { text: "#{room.creator.profile.nickname}の募集" },
          url: "https://gamers-room-f3c7adf17198.herokuapp.com/rooms/#{room.id}"
        }
      ]
    }

  connection.post("", data)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_message.html.erb
<div class="d-flex flex-column align-self-end">
  <div class="d-flex justify-content-end">
    <%= image_tag message.user.profile.decorate.avatar_image(40, 40), class: "rounded-circle", id: "message-avatar" %>
    <span><%= message.message_nickname %></span>
  </div>  
  <p class="align-self-end"><%= message.body %></p>
</div>

app/views/rooms/_permit.html.erb
<div class="d-flex" id="permit_<%= permit.id %>">
  <div class="dropdown">
    <div class="d-flex dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
      <%= image_tag permit.user.profile.decorate.avatar_image(40,40), class: "rounded-circle", id: "room-avatar" %>
      <span class="align-self-center ms-1" id="user-dropdown"><%= permit.user.profile.nickname %></span>
    </div>
    <ul class="dropdown-menu" id="drop_down">
      <li><%= link_to user_profile_path(permit.user), class: "dropdown-item" do %><i class="bi bi-person-circle me-1"></i><%= t(".profile") %><% end %></li>
      <li><%= link_to new_friend_path(permit.user), data: { turbo_method: :post }, class: "dropdown-item" do %><i class="bi bi-chat-dots me-1"></i><%= t(".friend") %><% end %></li>
      <li><%= link_to block_friend_path(permit.user), class: "dropdown-item link-danger", data: { turbo_method: :patch, turbo_confirm: t("sidebar.confirm_block") } do %><i class="bi bi-ban me-1"></i><%= t("sidebar.block_friend") %><% end %></li>
    </ul>
  </div>
</div>

app/views/rooms/_permit_button.html.erb
<div class="ms-auto me-1">
  <%= link_to t("default.approve"), approve_room_permit_path(permit.room, permit), data: { turbo_method: :post }, class: "btn btn-sm", id: "permit_primary_btn" %>
  <%= link_to t("default.refuse"), refuse_room_permit_path(permit.room, permit), data: { turbo_method: :delete }, class: "btn btn-sm", id: "permit_danger_btn" %>
</div>

app/views/rooms/_recruit_card.html.erb
<div class="card me-3 mt-3 flex-shrink-0" id="recruit-card">
  <%= image_tag room.game.decorate.picture_image(248, 150), size: "248x150", id: "game-picture" %> 
  <div class="card-body">
    <% if room.users.include?(current_user) %>
      <%= link_to chat_board_room_path(room), id: "room_title" do %>
        <h6 class="text-wrap"><%= room.title %></h6>
      <% end %>
    <% else %>    
      <%= link_to room_path(room), id: "room_title" do %>
        <h6 class="text-wrap"><%= room.title %></h6>
      <% end %>
    <% end %>
    <%= link_to search_rooms_path(q: { word: room.game.name }), id: "search" do %>
      <%= room.game.name %>
    <% end %>  
    <div class="d-flex">
      <%= image_tag room.creator.profile.decorate.avatar_image(25, 25), class: "rounded-circle", id: "card-avatar" %>
      <span class="align-self-end"><%= room.creator.profile.nickname %></span>
    </div>
    <div class="d-flex">
      <span><%= t(".people") %></span>
      <span class="ms-2"><%= room.users.count %>/<%= room.people %></span>
    </div>
    <div class="d-flex flex-wrap mb-2" id="tag-area">
      <% room.tags.each do |tag| %>
        <%= link_to search_rooms_path(q: { mode_tag: tag.id }), id: "search" do %>
          <span class="me-1"><%= tag.name %></span>
        <% end %>  
      <% end %>
    </div>
    <span><i class="bi bi-clock me-1"></i><%= l room.created_at,format: :time %></span>  
  </div>
</div>

app/views/rooms/_search_field.html.erb
<%= form_with url: search_rooms_path, method: :get, locals: true, scope: :q do |f| %>
  <div class="input-group">
    <div class="w-75">
      <%= f.text_field :word, class: "form-control", placeholder: t(".blank_text") %>
    </div>
    <div class="d-flex mt-2">  
      <%= f.select :mode_tag, @mode_tag_options.map { |tag| [tag.name, tag.id ] }, { include_blank: t(".mode_blank") }, class: "form-select me-2" %>
      <%= f.select :style_tag, @style_tag_options.map { |tag| [tag.name, tag.id ] }, { include_blank: t(".style_blank") }, class: "form-select me-2" %>
      <%= f.select :ability_tag, @ability_tag_options.map { |tag| [tag.name, tag.id ] }, { include_blank: t(".ability_blank") }, class: "form-select me-3" %>
      <div class="d-flex justify-content-center" id="search_btn_area">
        <%= f.submit t(".search"), class: "btn", id: "search_btn" %>
      </div>
    </div>  
  </div>  
<% end %>

app/views/rooms/chat_board.html.erb
<% breadcrumb :room_chat_board, @room %>
<div class="container" id="chat-board">
  <div class="row">
    <div class="col-md-3" id="join-user">
      <div class="d-flex flex-column">
        <div class="mt-5 py-3 ps-2" id="user-list">
          <h5><%= t(".joiner") %></h5>
          <% @users.each do |user| %>
            <div class="d-flex">
              <div class="dropdown">
                <div class="d-flex dropdown-toggle" data-bs-toggle="<%= 'dropdown' unless user == current_user %>" role="button" aria-expanded="false">
                  <%= image_tag user.profile.decorate.avatar_image(40,40), class: "rounded-circle", id: "room-avatar" %>
                  <span class="align-self-center ms-1" id="<%= 'user-dropdown' unless user == current_user %>"><%= user.profile.nickname %></span>
                  <% if current_user. blocked_user?(user) %>
                    <i class="bi bi-exclamation-circle" style="font-size: 1rem; color: red;"></i> 
                  <% end %>
                </div>      
                <ul class="dropdown-menu" id="drop_down">
                  <li><%= link_to user_profile_path(user), class: "dropdown-item" do %><i class="bi bi-person-circle me-1"></i><%= t(".profile") %><% end %></li>
                  <li><%= link_to new_friend_path(user), data: { turbo_method: :post },class: "dropdown-item" do %><i class="bi bi-chat-dots me-1"></i><%= t(".friend") %><% end %></li>
                  <li><%= link_to block_friend_path(user), class: "dropdown-item link-danger", data: { turbo_method: :patch, turbo_confirm: t("sidebar.confirm_block") } do %><i class="bi bi-ban me-1"></i><%= t("sidebar.block_friend") %><% end %></li>
                </ul>
              </div>
              <% if @room.creator == current_user && user != @room.creator %>
                <div class="ms-auto me-1">
                  <%= link_to t(".kick"), kick_user_room_path(@room, user), data: { turbo_method: :patch, turbo_confirm: t(".kick_confirm") }, class: "btn btn-sm", id: "permit_danger_btn" %>  
                </div>
              <% end %>
            </div>    
          <% end %>
        </div>  
        <div class="mt-5 py-3 ps-2" id="permit-user" data-id="<%= current_user.id %>">
            <p>
              <i class="bi bi-exclamation-circle" style="font-size: 1rem; color: red;"></i>
              はブロックしているユーザーです
            </p>
            <h5><%= t(".permiter") %></h5> 
            <div id="permit_user_field">
              <% @permits.each do |permit| %>
                <div class="d-flex" id="permit_<%= permit.id %>">
                  <div class="dropdown">
                    <div class="d-flex dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                      <%= image_tag permit.user.profile.decorate.avatar_image(40,40), class: "rounded-circle", id: "room-avatar" %>
                      <span class="align-self-center ms-1" id="user-dropdown"><%= permit.user.profile.nickname %></span>
                      <% if current_user.blocked_user?(permit.user) %>
                        <i class="bi bi-exclamation-circle" style="font-size: 1rem; color: red;"></i>
                      <% end %> 
                    </div>
                    <ul class="dropdown-menu" id="drop_down">
                      <li><%= link_to user_profile_path(permit.user), class: "dropdown-item" do %><i class="bi bi-person-circle me-1"></i><%= t(".profile") %><% end %></li>
                      <li><%= link_to new_friend_path(permit.user), data: { turbo_method: :post }, class: "dropdown-item" do %><i class="bi bi-chat-dots me-1"></i><%= t(".friend") %><% end %></li>
                      <li><%= link_to block_friend_path(permit.user), class: "dropdown-item link-danger", data: { turbo_method: :patch, turbo_confirm: t("sidebar.confirm_block") } do %><i class="bi bi-ban me-1"></i><%= t("sidebar.block_friend") %><% end %></li>
                    </ul>
                  </div>    
                  <% if @room.creator == current_user %>
                    <div class="ms-auto me-1">
                      <%= link_to t(".approve"), approve_room_permit_path(@room, permit), data: { turbo_method: :post }, class: "btn btn-sm", id: "permit_primary_btn" %>
                      <%= link_to t(".refuse"), refuse_room_permit_path(@room, permit), data: { turbo_method: :delete }, class: "btn btn-sm", id: "permit_danger_btn" %>
                    </div>  
                  <% end %>
                </div>   
              <% end %>
            </div>    
        </div>
      </div>
    </div>
    <div class="col-md-5">
      <div class="d-flex flex-column mt-5 p-3 overflow-auto" id="message-field" data-id="<%= @room.id %>">
        <% @messages.each do |message| %>
          <div class="d-flex flex-column <%= message.user == current_user ? 'align-self-end' : 'align-self-start' %>">
            <div class="d-flex justify-content-<%= message.user == current_user ? 'end' : 'start' %>">
              <%= image_tag message.user.profile.decorate.avatar_image(40, 40), class: "rounded-circle", id: "message-avatar" %>
              <span><%= message.message_nickname %></span>
            </div>  
            <p class="align-self-<%= message.user == current_user ? 'end' : 'start' %>"><%= message.body %></p>
          </div>
        <% end %>
      </div>
      <form class="mt-3">
        <input type="text" placeholder=<%= t("default.form_placeholder") %> class="form-control" name="message" id="message-form">
      </form>
    </div>
    <div class="col-md-3 mt-5">
      <div class="d-flex flex-column rounded" id="detail-field">
        <div class="mt-3 d-flex justify-content-center"> 
          <div>
            <h5><%= @room.title %></h5>
            <h6><%= @room.game.name %></h6>
            <div class="d-flex flex-wrap mb-2" id="tag-area">
              <% @room.tags.each do |tag| %>
              <span class="mb-1"><%= tag.name %></span>
              <% end %>
            </div>
            <div class="d-flex">
              <div><span><%= t(".people") %><span></div>
              <span class="ms-2"><%= @room.users.count %>/<%= @room.people %></span>
            </div>
          </div>
        </div>    
        <div class="p-2"><%= simple_format(@room.body) %></div>
        <div class="d-flex justify-content-center">
          <% if @room.creator == current_user %>
            <div class="d-flex justify-content-center me-2" id="edit_btn_area">
              <%= link_to edit_room_path(@room), class: "btn", id: "edit_btn" do %><i class="bi bi-pencil-square me-2"></i><%= t("default.edit") %><% end %>
            </div>
          <% end %>
          <div class="d-flex justify-content-center me-2" id="delete_btn_area">
            <%= link_to leave_room_path(@room), class: "btn", data: { turbo_method: :delete, turbo_confirm: t(".leave_confirm") },id: "delete_btn" do %><i class="bi bi-door-open me-1"></i><%= t(".leave") %><% end %>
          </div>
        </div>
        <div class="d-flex justify-content-center mt-2">
          <div class="d-flex justify-content-center" id="discord_btn_area">
            <a href="https://discord.gg/ZxFyMFjDNq" target="_blank" class="btn" id="discord_btn"><i class="bi bi-discord me-1"></i><%= t("default.discord_btn") %></a>
          </div>
        </div>  
      </div> 
      <div class="twitter d-flex justify-content-center mt-3">
        <%= link_to "https://twitter.com/share?url=#{room_url(@room)}&text=【gamers room】%0a パーティーに参加して一緒にプレイしよう！ %0a#{@room.title}&hashtags=#{@room.game.name},ゲーム募集", target: '_blank', data: { toggle: "tooltip", placement: "bottom" }, title: "Xでシェア" do %>
          <i class="bi bi-twitter-x" id="twitter"></i>
        <% end %>
      <div> 
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<% breadcrumb :room_index %>
<% set_meta_tags title: t(".title") %>
<div class="container" id="room-index">
  <div class="row">
    <div class="col-md-4 offset-md-2 my-3 d-flex">
      <h2 class="mt-3"><%= t(".title") %></h2>
      <div class="d-flex justify-content-center mt-3 ms-5" id="bg_success_btn_area">
        <%= link_to new_room_path, class: "btn", id: "bg_success_btn" do %><i class="bi bi-pencil me-1"></i><%= t(".create") %><% end %>
      </div>  
    </div>
    <div class="col-md-5 mt-2 ms-4">
      <%= render "search_field" %>
    </div>
  </div>
  <% if user_signed_in? %>
    <div class="row">
      <div class="col-md-10 offset-md-1" id="rectuit-area">
        <% if @joined_rooms.present? %>
          <h3><%= t(".joined_room") %></h3>
          <div class="d-flex flex-wrap">
            <% @joined_rooms.each do |room| %>
              <%= render partial: 'recruit_card', locals: { room: room } %>
            <% end %>
          </div>
        <% end %>  
      </div>
    </div>
  <% end %>  
  <div class="row">
    <div class="col-md-10 offset-md-1 mt-5" id="rectuit-area">
      <h3><%= t(".seeking") %></h3>
      <div class="d-flex flex-wrap">
        <% @rooms.each do |room| %>
          <%= render partial: 'recruit_card', locals: { room: room } %>
        <% end %>
      </div>
      <div class="d-flex justify-content-center mt-3">
        <%= paginate @rooms, window: 3, theme: "bootstrap-5" %>
      </div>  
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<% breadcrumb :room_show, @room %>
<div class="container" id="rooms-show-page">
  <div class="row">
    <div class="col-md-5 offset-md-2 mt-5 p-4 d-flex justify-content-center rounded" id="show-area">
      <div>
        <h3><%= @room.title %></h3>
        <h5><%= @room.game.name %></h5>
        <div class="d-flex mt-2">
          <%= image_tag @room.creator.profile.decorate.avatar_image(50, 50),class: "rounded-circle", id: "show-avatar" %>
          <div class="align-self-center"><h5><%= @room.creator.profile.nickname %></h5></div>
        </div>
        <div class="d-flex flex-wrap my-2" id="tag-area">
          <% @room.tags.each do |tag| %>
            <span class="mb-1"><%= tag.name %></span>
          <% end %>
        </div>
        <div class="d-flex my-2">
          <h6><%= t(".people") %></h6>
          <h6 class="ms-2"><%= @room.users.count %>/<%= @room.people %></h6>
        </div>
        <div id="description"><%= simple_format(@room.body) %></div>
        <% if  @room.permit_users.include?(current_user) %>
          <div class="d-flex justify-content-center" id="bg_delete_btn_area">
            <%= link_to room_permit_path(@room, @room.find_permit(current_user)), data: { turbo_method: :delete }, class: "btn", id: "bg_delete_btn" do %>
              <i class="bi bi-x-circle me-1"></i><%= t("default.not_join") %>
            <% end %>
          </div>  
        <% elsif @room.people == @room.users.count %>
          <div class="d-flex justify-content-center" id="full_btn_area">
            <button class="pb-1" id="full_btn"><i class="bi bi-people-fill me-1" disabled></i><%= t(".full") %></button>
          </div>
        <% else %>
          <% if @room.have_blocked_user?(current_user) %>
            <div class="d-flex justify-content-center" id="bg_success_btn_area">
              <%= link_to room_permits_path(@room), data: { turbo_method: :post, turbo_confirm: t(".permit_confirm") }, class: "btn", id: "bg_success_btn" do %>
                <i class="bi bi-box-arrow-in-right me-1"></i><%= t("default.application") %>
              <% end %>
            </div>  
          <% else %>
            <div class="d-flex justify-content-center" id="bg_success_btn_area">
              <%= link_to room_permits_path(@room), data: { turbo_method: :post }, class: "btn", id: "bg_success_btn" do %>
                <i class="bi bi-box-arrow-in-right me-1"></i><%= t("default.application") %>
              <% end %>  
            </div>  
          <% end %>  
        <% end %>
      </div>
    </div>
  </div>  
</div>