config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # email_check_env
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # check_sidekiq
  require "sidekiq/web"
  require "sidekiq-scheduler/web"
  mount Sidekiq::Web => "/sidekiq"

  # for_my_app_route
  root "static_page#top"
  resource :description, only: %i[show]

  resource :setting, only: %i[show]
  get "agreement", to: "settings#agreement", as: "agreement"
  get "plivacy_policy", to: "settings#privacy_policy", as: "plivacy_policy"
  resource :contact, only: %i[show new create]

  resource :profile, only: %i[new create edit update]
  get "profile/:id", to: "profiles#show", as: "user_profile"

  resources :notifications, only: %i[index]

  get "friends/:id", to: "friends#chat_board", as: "friend_chat"
  post "friends/:user_id", to: "friends#create", as: "new_friend"
  put "friends/:id", to: "friends#approve", as: "approve_friend"
  delete "friends/:id", to: "friends#refuse", as: "refuse_friend"
  patch "friend/:user_id", to: "friends#blocked", as: "block_friend"


  resources :rooms, only: %i[new index show create edit update destroy] do
    collection do
      get :search
    end
    member do
      get :chat_board
      delete :leave
      patch "kick/:user_id", to: "rooms#kick", as: :kick_user
    end
    resources :permits, only: %i[create destroy] do
      member do
        post :approve
        delete :refuse
      end
    end
  end

  resources :boards, only: %i[new index show create destroy] do
    collection do
      get :search
    end
    resources :comments, only: %i[create] do
      get "media_show/:id", to: "comments#media_show", as: "media"
    end
  end

  # for_admin_route
  namespace :admin do
    root "dashboards#index"
    resource :dashboard, only: %i[index]
    devise_scope :user do
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      delete "logout", to: "sessions#destroy"
      get "user_edit/:id", to: "registrations#edit", as: "user_edit"
      put "user_update/:id", to: "registrations#update", as: "user_update"
      delete "user_destroy/:id", to: "registrations#destroy", as: "user_destroy"
    end
    resources :users, only: %i[index show] do
      collection do
        get :search
      end
    end
    resources :profiles, only: %i[show edit update]
    resources :rooms, only: %i[index show destroy] do
      collection do
        get :search
      end
    end
    resources :messages, only: %i[destroy]
    resources :games, only: %i[index create destroy]
    resources :tags, only: %i[index create destroy]
    resources :contacts, only: %i[index show destroy] do
      collection do
        get :search
      end
    end
    resources :boards, only: %i[index show destroy] do
      collection do
        get :search
      end
      resources :comments, only: %i[destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [ :google_oauth2 ]

  has_one :profile, dependent: :destroy
  has_many :rooms, class_name: "Room", foreign_key: "creator_id", dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :send_notifications, class_name: "Notification", foreign_key: "sender_id", dependent: :destroy
  has_many :receive_notifications, class_name: "Notification", foreign_key: "receiver_id", dependent: :destroy
  has_many :leader_friends, class_name: "Friend", foreign_key: "leader_id", dependent: :destroy
  has_many :follower_friends, class_name: "Friend", foreign_key: "follower_id", dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :boards, class_name: "Board", foreign_key: "creator_id", dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :first_name,  length: { maximum: 255 }
  validates :last_name,  length: { maximum: 255 }
  validate :first_name_cannot_be_nil
  validate :last_name_cannot_be_nil
  validates :email, presence: true, uniqueness: true
  validates :role, presence: true
  validates :uid, presence: true, uniqueness: { scope: :provider }, if: -> { provider.present? }

  enum role: { general: 0, admin: 1 }

  def first_name_cannot_be_nil
    errors.add(:first_name, "can't be nil") if first_name.nil?
  end

  def last_name_cannot_be_nil
    errors.add(:last_name, "can't be nil") if last_name.nil?
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      names = auth.info.name.split(" ", 2)
      user.last_name = names[0]
      user.first_name = names[1] || ""
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.password_confirmation = user.password
    end
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def find_friend(user)
    self.leader_friends.find_by(follower: user) || self.follower_friends.find_by(leader: user)
  end

  def blocked_user?(user)
    blocked_users = self.follower_friends.where(category: 2).map { |f| f.leader }
    blocked_users.any?(user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def  index
    @users = User.all.order(id: :DESC)
  end

  def show
    @user = User.find(params[:id])
    @profile = @user.profile
  end

  def search
    @user_search = AdminUserSearchForm.new(search_params)
    @users = @user_search.result
  end

  private

  def search_params
    params.require(:q).permit(:first_name, :last_name, :role_name, :sort)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :google_oauth2
  skip_before_action :authenticate_user!
  skip_before_action :profile_check
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  def google_oauth2
    callback_for(:google_oauth2)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:success, :success, kind: provider.to_s.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_session_path
    end
  end

  # GET|POST /users/auth/twitter/callback
  def failure
    redirect_to new_user_session_path, danger: t(".failure")
  end

  protected

  def after_sign_in_path_for(resource)
    if resource.profile.blank?
      new_profile_path
    else
      root_path
    end
  end
  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  skip_before_action :authenticate_user!
  skip_before_action :profile_check
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      flash.clear
      set_flash_message!(:success, :password_reset_mail)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      flash.clear
      set_flash_message!(:danger, :password_reset_mail_failed)
      respond_with(resource)
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?

    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      if resource_class.sign_in_after_reset_password
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message!(:success, flash_message)
        resource.after_database_authentication
        sign_in(resource_name, resource)
      else
        set_flash_message!(:success, :updated_not_active)
      end
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      set_minimum_password_length
      respond_with resource
    end
  end

  # protected
  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  skip_before_action :authenticate_user!, only: %i[ new create edit update ]
  skip_before_action :profile_check, only: %i[ new create edit update ]
  before_action :configure_permitted_parameters, only: %i[ create update ]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :success, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :success, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  def build_resource(hash = {})
    hash[:uid] = User.create_unique_string
    super
  end

  def update_resource(resource, params)
    return super if params["password"].present?

    resource.update_without_password(params.except("current_password"))
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name, :role ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :first_name, :last_name ])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_sign_up_path_for(resource)
    new_profile_path
  end

  def after_update_path_for(resource)
    setting_path
  end

  def set_flash_message_for_update(resource, prev_unconfirmed_email)
    return unless is_flashing_format?

    flash_key = if update_needs_confirmation?(resource, prev_unconfirmed_email)
      :update_needs_confirmation
    elsif sign_in_after_change_password?
      :updated
    else
      :updated_but_not_signed_in
    end
    set_flash_message :success, flash_key
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  skip_before_action :authenticate_user!, only: %i[ new create ]
  skip_before_action :profile_check, only: %i[ new create ]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate(auth_options)

    if resource
      set_flash_message!(:success, :signed_in)
      sign_in(resource_name, resource)
      redirect_to after_sign_in_path_for(resource)
    else
      self.resource = resource_class.new(sign_in_params)
      flash.now[:danger] = t("devise.sessions.signed_in_failed")
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :success, :signed_out if signed_out
    yield if block_given?
    respond_to_on_destroy
  end

  # protected
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/users/_search_form.html.erb
<%= form_with url: search_admin_users_path, scope: :q, method: :get, locals: true do |f| %>
  <div class="d-flex">
    <%= f.text_field :last_name, class: "form-control", placeholder: "姓" %>
    <%= f.text_field :first_name, class: "form-control ms-1", placeholder: "名" %>
  </div>  
  <div class="d-flex mt-2">
    <%= f.select :role_name, User.roles.keys.map{ |k| [t("enums.user.role.#{k}"), k]}, { include_blank: t("admin.helpers.role") }, class: "form-select" %>
    <%= f.select :sort, [["降順", 0], ["昇順", 1]], { include_blank: t("admin.helpers.sort") }, class: "form-select ms-2" %>
    <%= f.submit t('admin.helpers.search'), class: "btn btn-primary ms-2" %>
  </div>  
<% end %>  

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= user.decorate.fullname %></td>
  <td><%= user.decorate.role_status %></td>
  <td><%= user.email %></td>
  <td><%= link_to t('default.show'), admin_user_path(user), class: 'btn btn-primary' %></td>
  <td><%= link_to t('default.edit'), admin_user_edit_path(user), class: 'btn btn-success' %></td>
  <td><%= link_to t('default.delete'), admin_user_destroy_path(user), data: { turbo_method: :delete, turbo_confirm: t(".destroy") }, class: 'btn btn-danger' %></td>
</tr>

app/views/admin/users/index.html.erb
<% set_meta_tags title: t(".title") %>
<div class='container'>
  <div class='row my-4'>
    <div class='col-md-4'>
      <h1><%= t(".title") %></h1>
    </div>   
  </div>
  <div class='row'>
    <div class='col-md-8'>
      <table class="table">
        <thead>
         <tr>
          <th scope="col"><%= User.human_attribute_name(:id) %></th>
          <th scope="col"><%= User.human_attribute_name(:fullname) %></th>
          <th scope="col"><%= User.human_attribute_name(:role) %></th>
          <th scope="col"><%= User.human_attribute_name(:email) %></th>
          <th scope="col"></th>
         </tr>
        </thead>
        <tbody>
          <%= render partial: 'user', collection: @users %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/search.html.erb
<% set_meta_tags title: t(".title") %>
<div class='container'>
  <div class='row my-4'>
    <div class='col-md-4'>
      <h1><%= t(".title") %></h1>
    </div>
    <div class="col-md-3">
      <%= render 'search_form' %>
    </div>  
  </div>
  <div class='row'>
    <div class='col-md-8'>
      <table class="table">
        <thead>
         <tr>
          <th scope="col"><%= User.human_attribute_name(:id) %></th>
          <th scope="col"><%= User.human_attribute_name(:fullname) %></th>
          <th scope="col"><%= User.human_attribute_name(:role) %></th>
          <th scope="col"><%= User.human_attribute_name(:email) %></th>
          <th scope="col"></th>
         </tr>
        </thead>
        <tbody>
          <%= render partial: 'user', collection: @users %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<% set_meta_tags title: t(".title") %>
<div class="container">
  <div class="row p-5">
    <div class="col-md-4 mt-3">
      <h3><%= t(".title") %></h3>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row"><%= User.human_attribute_name(:id) %></th>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <th scope="row"><%= User.human_attribute_name(:fullname) %></th>
            <td><%= @user.decorate.fullname %></td>
          </tr>
          <tr>
            <th scope="row"><%= User.human_attribute_name(:email) %></th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th scope="row"><%= User.human_attribute_name(:role) %></th>
            <td><%= @user.decorate.role_status %></td>
          </tr>
        </tbody>
      </table>
      <div>
        <%= link_to t('default.edit'), admin_user_edit_path(@user), class: 'btn btn-success' %>
        <%= link_to t('default.delete'), admin_user_destroy_path(@user), data: { turbo_method: :delete, turbo_confirm: t(".destroy") }, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
  <div class="row p-5" id="admin-profile">
    <div class="col-md-10">
      <h3><%= t(".profile") %></h3>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row"><%= Profile.human_attribute_name(:nickname) %></th>
            <td><%= @profile.nickname %></td>
          </tr>
          <tr>
            <th scope="row"><%= Profile.human_attribute_name(:sex) %></th>
            <td><%= @profile.decorate.profile_sex %></td>
          </tr>
          <tr>
            <th scope="row"><%= Profile.human_attribute_name(:introduction) %></th>
            <td><%= simple_format(@profile.introduction) %></td>
          </tr>
          <tr>
            <th scope="row"><%= Profile.human_attribute_name(:avatar) %></th>
            <td><%= image_tag @profile.decorate.avatar_image(100, 100), id: "admin-avatar" %></td>
          </tr>
        </tbody>
      </table>
      <div>
        <%= link_to t('default.edit'), edit_admin_profile_path(@profile), class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>